name: ThemeCheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        version:
          - 3.0.0
          - 2.7.1
          - 2.6.6

    name: Ruby ${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Install dependencies
        run: bundle install --jobs=3 --retry=3
      - name: Run tests
        run: bundle exec rake
      - name: Test runtime
        # Testing that runtime can execute, not testing the results themselves
        run: bundle exec theme-check ./test/theme | grep -q "files inspected"
